### ISSUE TITLE
Standalone Neural Ranking Model (SNRM)

### ISSUE THREAD

**Issue by hamed-zamani** [felipemoraes/se-recsys-paperswithcode#2]
“From Neural Re-Ranking to Neural Ranking: Learning a Sparse Representation for Inverted Indexing” In the Proceedings of CIKM 2018.

Code: https://github.com/hamed-zamani/snrm
Paper: https://dl.acm.org/citation.cfm?id=3271800

**Comment by felipemoraes** [comment]
Thanks @hamed-zamani!
